version: 1
workflow_path: template.yaml
generate_name: True

secrets:
  - node_selector: all
    secret_name: gargantua-secrets
  - node_selector: all
    secret_name: ada-prod-secrets

env_variables:
  - node_selector: all
    envs:
      GIT_BRANCH: "dev"
      PROJECT_DIR: "/medchem"
      DATA: "gs://screening-libraries/zinc-available/zinc-processed-v1.parquet"
      OUTPUT_PATH: "gs://screening-libraries/zinc-available/stats-v1/zinc-processed-{partition_name}.csv"

machines:
  - node_selector: all
    machine_name: greedy-pool-32-preemptible
