apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: complexity-zinc
  labels:
    organization: internal
    project: izanagi-chempile
    run: druglike-filter

spec:
  entrypoint: entrypoint

  templates:
    - name: entrypoint
      dag:
        tasks:
          - name: distribute-partition
            template: distribute-partition

          - name: compute
            template: compute
            dependencies: [distribute-partition]
            arguments:
              parameters:
                - name: partition
                  value: "{{item}}"
            withParam: "{{tasks.distribute-partition.outputs.result}}"

    - name: distribute-partition
      script:
        image: condaforge/miniforge3
        command: [python]
        source: |
          import json
          PARTITION_START = 0
          PARTITION_END = 64
          outputs = []
          for i in range(PARTITION_START, PARTITION_END):
              outputs.append(f"PARTITION_{i:02d}")
          print(json.dumps(outputs))
    - name: compute
      inputs:
        parameters:
          - name: partition
      script:
        image: gcr.io/platform-iv/partner-projects-crl-angelini:main
        command: [bash, --login]
        source: |
          SCREENING_DB_PARTITION="{{inputs.parameters.partition}}"
          # Log to anaconda with `VALENCE_ANACONDA_TOKEN`
          valence_login_to_conda
          # Clone project dir
          valence_clone_and_install valence-platform/medchem \
            --repo-dir $PROJECT_DIR \
            --branch $GIT_BRANCH \
            --private
          cd $PROJECT_DIR
          conda activate $CONDA_ENV
          apt update
          apt install build-essential -y

          pip install --no-deps -vv  -e .
          cd $PROJECT_DIR/workflow/complexity/
          # Enable conda env
          mamba env list
          echo "Start processing partition $SCREENING_DB_PARTITION"
          python script.py \
            --partition-name $SCREENING_DB_PARTITION --input-path $DATA --output-path $OUTPUT_PATH
