name: code-check

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch Valence Actions
        uses: actions/checkout@v3
        with:
          repository: valence-platform/valence-actions
          ref: latest
          token: ${{ secrets.VALENCE_GITHUB_TOKEN_PLATFORM }}
          path: .github/valence-actions

      - name: Code Check
        uses: ./.github/valence-actions/code-check
        with:
          python-version: "3.8"
          black-enable: true
          mypy-enable: false
