name: doc

on:
  push:
    branches:
      - "master"

jobs:
  doc:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 3
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ runner.os }}-${{ env.CACHE_NUMBER }}-${{ hashFiles('env.yml') }}

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@master # TODO: pin once 2.1 released.
        with:
          miniforge-variant: Mambaforge
          use-mamba: true
          use-only-tar-bz2: true
          activate-environment: medchem

      - name: Anaconda Login
        env:
          ANACONDA_USER_TOKEN: ${{ secrets.INVIVOAI_ANACONDA_USER_BOT_TOKEN }}
        run: |
          # Bypass the installation of anaconda-client
          TOKEN_DIR="$HOME/.config/binstar"
          TOKEN_PATH="$TOKEN_DIR/https%3A%2F%2Fapi.anaconda.org.token"
          mkdir -p $TOKEN_DIR
          echo -e "${ANACONDA_USER_TOKEN}\c" > $TOKEN_PATH

      - name: Setup conda env
        run: |
          mamba env update -f env.yml

      - name: Install library
        run: |
          python -m pip install .

      - name: Deploy the doc
        run: |

          # Get the privpage branch
          git fetch origin privpage

          # Build and serve the doc
          mkdocs gh-deploy
