name: doc

on:
  push:
    branches:
      - "master"

jobs:
  doc:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Fetch Valence Actions
        uses: actions/checkout@v2
        with:
          repository: valence-platform/valence-actions
          ref: main
          token: ${{ secrets.VALENCE_GITHUB_TOKEN_PLATFORM }}
          path: .github/valence-actions

      - name: Build and deploy the documentation
        uses: ./.github/valence-actions/deploy-valdoc
        with:
          env-name: medchem
          env-file: env.yml
          install-editable: true
          anaconda-token: ${{ secrets.INVIVOAI_ANACONDA_USER_BOT_TOKEN }}
          valdoc-json-key: ${{ secrets.VALDOC_WRITE_JSON_KEY }}
