name: test

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"

jobs:
  build-test:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Fetch Valence Actions
        uses: actions/checkout@v2
        with:
          repository: valence-platform/valence-actions
          ref: latest
          token: ${{ secrets.VALENCE_GITHUB_TOKEN_PLATFORM }}
          path: .github/valence-actions

      - name: Build and Test
        uses: ./.github/valence-actions/build-test
        with:
          env-name: medchem
          env-file: env.yml
          anaconda-token: ${{ secrets.INVIVOAI_ANACONDA_USER_BOT_TOKEN }}
          test-command: pytest -x -v
          test-cli-command: chemfilter --help
          test-doc-command: mkdocs build
