name: weekly-test

on:
  push:
    branches:
      - "main"
  workflow_dispatch: {}
  schedule:
    - cron: "0 4 * * MON"

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
        rdkit-version: ["2021.09", "2022.03", "2022.09"]
        exclude:
          - python-version: 3.10
            rdkit-version: 2021.09

    runs-on: "ubuntu-latest"
    timeout-minutes: 30

    defaults:
      run:
        shell: bash -l {0}

    name: |
      python=${{ matrix.python-version }} -
      rdkit=${{ matrix.rdkit-version }} -

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Fetch Valence Actions
        uses: actions/checkout@v3
        with:
          repository: valence-platform/valence-actions
          ref: latest
          token: ${{ secrets.VALENCE_GITHUB_TOKEN_PLATFORM }}
          path: .github/valence-actions

      - name: Build and Test
        uses: ./.github/valence-actions/build-test
        with:
          env-name: medchem
          env-file: env.yml
          anaconda-token: ${{ secrets.INVIVOAI_ANACONDA_USER_BOT_TOKEN }}
          install-editable: true # require for pytest-cov to work...
          test-command: pytest -x -v
          test-cli-command: chemfilter --help
          test-doc-command: mkdocs build
          extra-specs: |
            python=${{ matrix.python-version }}
            rdkit=${{ matrix.rdkit-version }}
